production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=smart-atm --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
